sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tkPIL+/L7jb4uKegCKHSp5SFwmzx+qq2Q1TZBY38Oo4J9HhcpqKp1mofy6AtU6R+mR99k+wdY16e1uquFz71IdD2wGP90Z+LdkTR9SMenKTPw38yg5aAfbQiUfT2QMQLTcxswSZN3M7uLRcelx2l5GhP9/tq6rI3Vapijbq+IkjbGg5p+tsnTCXP1Z0O7J9cQF7FOqgOGVZLLj+P7yG23Av6GpMgWtvQShAKWwoYsPNJla5IAfclJAGj+AVokrCdiKu8NRxHblDYpKRvNZ+Z1YC6CqMJPpr5gC+gPmS4c8wh9VDFwqrDjkiPbFijVsX99neePfpvmLn8fAWuXC9GsUYLEvJVWEpcM7PmQQDNs8SKcQ8HGKgqAqSxMJq71Y/ZvbEo5HD4bVnllbxL+oDjF8U2xO28gr9/tYiqcexDDhbUakBRITyoJotWjCzSJuBdQ5Atlsmf66DZiYSl887/TaCRG9eVmjz2V/KS115gf7fQo4f2kxZhe5sVUniC7wTGXvCscO45IC4ieV8F8lX5ELCGSRrEcB65QXvnEaBo3trE1cfWBPRyxrX0nNJwl6tWmLvgQz+ednAbLbqVC7ZqvjGNwHxhZan9HgR1qFhQAORlOpYaTlc0jrE1f9JndZojBqgBs3rjMvcaB3UJsLq11vho3tfXVj2cn6xV79D5zSM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Sons-and-Lovers_217
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy